# Makefile.sub for ./src/media


# source modules, include all sub modules if any


# source for current module only
SRC_MEDIA += cmd-nms.c \
             client-nms.c \
             av-io-buffer.c \
             av-double-buffer.c \
             lock-control.c


# include the description for each sub module if any

