# Makefile.sub for ./src/test


# source modules, include all sub modules if any


# source for current module only
SRC_CORE += test-codec.c \
            test-i18n.c


SRC +=$(SRC_DEMOS)

# include the description for each sub module if any

