# Makefile.sub for ./media/include


# source modules, include all sub modules if any


# update modules


# source for current module only
SRC_MEDIA += 


# include the description for each sub module if any

